//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Order { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ID_Status { get; set; }
        public int ID_Client { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public Nullable<int> ID_Equipment { get; set; }
        public Nullable<int> ID_Service { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Services Services { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public string ClientFullName
        {
            get
            {

                return Clients != null ? $"{Clients.Surname} {Clients.Name} {Clients.Patronymic}" : "---";
            }
        }


        public string EmployeeFullName
        {
            get
            {

                return Employees != null ? $"{Employees.Surname} {Employees.Name}" : "Не назначен";
            }
        }


        public decimal TotalPrice
        {
            get
            {
                decimal sum = 0;


                if (Equipment != null) sum += Equipment.Price;


                if (Services != null) sum += Services.Price;

                return sum;
            }
        }


        public string StatusColor
        {
            get
            {
               
                if (OrderStatus == null || string.IsNullOrEmpty(OrderStatus.StatusName))
                    return "Transparent";

                
                switch (OrderStatus.StatusName.Trim().ToLower())
                {
                    case "новый":
                        return "#007BFF"; 

                    case "в работе":
                        return "#FFC107"; 

                    case "выполнен":
                        return "#A8E4A0"; 

                    case "отменен":
                        return "#DC3545"; 

                    default:
                        return "Transparent"; 
                }
            }
        }
    }
}

    

